### ISSUE TITLE
Add a warning/note that antivirus softwares may cause streampi to not work perfectly, often resulting in unexpected behaviour

### ISSUE THREAD

**Issue by rnayabed** [stream-pi/website#10]
This will be a part of the download page, both in the install instructions and at the top

**Comment by SamuelQuinones** [comment]
proposed implementation in 84aa309

**Comment by SamuelQuinones** [comment]
improvement pushed in 0833cb9

**Comment by rnayabed** [comment]
Antiviruses detect streampi to be a virus because it uses a VBS starter file, which is very unconventional for any software. Also, VBS is a very common lanugage to write viruses for windows, since its very easy to learn and read. The best way here would be to make an EXE of the vbs and pray that it works. the best method would be to get it signed by microsoft, and obtaining a developer certificate will cost you a ton of money

**Comment by SamuelQuinones** [comment]
Finished with 7a506f6
