### ISSUE TITLE
Output audio popping when the same audio clip is played repeatedly

### ISSUE THREAD

**Issue by frenksisco** [stream-pi/website#29]
When I click repeatedly and quickly on a button to play several times an audio clip in a short time I always hear a kind of "prr" or "pop" between one sound and the next.
Is there a solution? All my audio files are 44,100 Hz mono wav
Thanks

**Comment by SamuelQuinones** [comment]
@frenksisco not sure why this issue was made for the website,

Closing as it seems to be related to the client / server
